name: download_repository
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  permission_handler: ^11.3.1
  id3_codec: ^1.0.3
  dio: ^5.4.3+1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
